# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'minduspa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Alamofire'

  # Pods for minduspa

  target 'minduspaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'minduspaUITests' do
    # Pods for testing
  end

end
